import type { SoundDefinition } from '@/types/sound';

export const SOUND_CATALOG: SoundDefinition[] = [
  {
    id: 'rain-gentle',
    name: 'Gentle Rain',
    category: 'weather',
    description: 'Soft rainfall on a quiet afternoon',
    audioUrl: 'https://cdn.freesound.org/previews/501/501243_8644110-lq.mp3',
    color: '#8b5cf6',
    gradientFrom: '#7c3aed',
    gradientTo: '#a78bfa',
    defaultVolume: 0.6,
  },
  {
    id: 'rain-heavy',
    name: 'Heavy Rain',
    category: 'weather',
    description: 'Intense downpour with rhythmic patter',
    audioUrl: 'https://cdn.freesound.org/previews/321/321171_5121236-lq.mp3',
    color: '#6366f1',
    gradientFrom: '#4f46e5',
    gradientTo: '#818cf8',
    defaultVolume: 0.5,
  },
  {
    id: 'thunder',
    name: 'Thunderstorm',
    category: 'weather',
    description: 'Distant rolling thunder with rain',
    audioUrl: 'https://cdn.freesound.org/previews/425/425174_8323418-lq.mp3',
    color: '#a855f7',
    gradientFrom: '#9333ea',
    gradientTo: '#c084fc',
    defaultVolume: 0.4,
  },
  {
    id: 'ocean-waves',
    name: 'Ocean Waves',
    category: 'water',
    description: 'Rhythmic waves crashing on shore',
    audioUrl: 'https://cdn.freesound.org/previews/157/157880_177850-lq.mp3',
    color: '#06b6d4',
    gradientFrom: '#0891b2',
    gradientTo: '#22d3ee',
    defaultVolume: 0.6,
  },
  {
    id: 'creek',
    name: 'Forest Creek',
    category: 'water',
    description: 'Babbling brook through the woods',
    audioUrl: 'https://cdn.freesound.org/previews/671/671883_9551767-lq.mp3',
    color: '#0ea5e9',
    gradientFrom: '#0284c7',
    gradientTo: '#38bdf8',
    defaultVolume: 0.5,
  },
  {
    id: 'waterfall',
    name: 'Waterfall',
    category: 'water',
    description: 'Powerful cascading waterfall',
    audioUrl: 'https://cdn.freesound.org/previews/429/429137_8214298-lq.mp3',
    color: '#14b8a6',
    gradientFrom: '#0d9488',
    gradientTo: '#2dd4bf',
    defaultVolume: 0.4,
  },
  {
    id: 'birds-morning',
    name: 'Morning Birds',
    category: 'wildlife',
    description: 'Dawn chorus of songbirds',
    audioUrl: 'https://cdn.freesound.org/previews/649/649862_1661766-lq.mp3',
    color: '#10b981',
    gradientFrom: '#059669',
    gradientTo: '#34d399',
    defaultVolume: 0.5,
  },
  {
    id: 'crickets',
    name: 'Night Crickets',
    category: 'wildlife',
    description: 'Chirping crickets on a warm evening',
    audioUrl: 'https://cdn.freesound.org/previews/479/479041_1661766-lq.mp3',
    color: '#22c55e',
    gradientFrom: '#16a34a',
    gradientTo: '#4ade80',
    defaultVolume: 0.5,
  },
  {
    id: 'frogs',
    name: 'Night Frogs',
    category: 'wildlife',
    description: 'Frogs croaking near a pond',
    audioUrl: 'https://cdn.freesound.org/previews/379/379828_6647641-lq.mp3',
    color: '#84cc16',
    gradientFrom: '#65a30d',
    gradientTo: '#a3e635',
    defaultVolume: 0.4,
  },
  {
    id: 'fire',
    name: 'Crackling Fire',
    category: 'environment',
    description: 'Warm fireplace with crackling logs',
    audioUrl: 'https://cdn.freesound.org/previews/729/729396_12863902-lq.mp3',
    color: '#f59e0b',
    gradientFrom: '#d97706',
    gradientTo: '#fbbf24',
    defaultVolume: 0.5,
  },
  {
    id: 'wind',
    name: 'Gentle Wind',
    category: 'atmosphere',
    description: 'Soft breeze through open fields',
    audioUrl: 'https://cdn.freesound.org/previews/341/341840_4965320-lq.mp3',
    color: '#f43f5e',
    gradientFrom: '#e11d48',
    gradientTo: '#fb7185',
    defaultVolume: 0.4,
  },
  {
    id: 'forest',
    name: 'Forest Ambience',
    category: 'atmosphere',
    description: 'Deep forest with rustling leaves',
    audioUrl: 'https://cdn.freesound.org/previews/547/547922_189568-lq.mp3',
    color: '#ec4899',
    gradientFrom: '#db2777',
    gradientTo: '#f472b6',
    defaultVolume: 0.5,
  },
];

export function getSoundById(id: string): SoundDefinition | undefined {
  return SOUND_CATALOG.find(s => s.id === id);
}
